language: python
python:
  - "2.7"
  - "2.6"
  - "3.3"
env:
  - DJANGO_PACKAGE=Django==1.5.1
  - DJANGO_PACKAGE=https://github.com/django/django/archive/stable/1.6.x.zip
install:
  - pip install -q $DJANGO_PACKAGE --use-mirrors
  - python setup.py install
script: make test
